=begin
#Flip API

#Description

OpenAPI spec version: 3.1.0
Contact: cloudsupport@telestream.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'date'

module TelestreamCloud::Flip

  class VideoUploadBody
    # Size of the file that will be uploaded in `bytes`.
    attr_accessor :file_size

    # Name of the file that will be uploaded.
    attr_accessor :file_name

    # A list of names of additional files that will be uploaded.
    attr_accessor :extra_files

    # A comma-separated list of profile names or IDs to be used during encoding. Alternatively, specify none so no encodings will created right away.
    attr_accessor :profiles

    attr_accessor :path_format

    # Payload is an arbitrary text of length 256 or shorter that you can store along the Video. It is typically used to retain an association with one of your own DB record ID.
    attr_accessor :payload

    attr_accessor :extra_variables

    # URL pointing to an image that will be used asa watermark.
    attr_accessor :watermark_url

    # Determines distance between the left edge of a video and the left edge of a watermark image. Can be specified in pixels or percents. This parameter can be set only if watermark_right is not.
    attr_accessor :watermark_left

    # Determines distance between the top edge of a video and the top edge of a watermark image. Can be specified in pixels or percents. This parameter can be set only if watermark_bottom is not.
    attr_accessor :watermark_top

    # Determines distance between the right edge of a video and the right edge of a watermark image. Can be specified in pixels or percents. This parameter can be set only if watermark_left is not.
    attr_accessor :watermark_right

    # Determines distance between the bottom edge of a video and the bottom edge of a watermark image. Can be specified in pixels or percents. This parameter can be set only if watermark_top is not.
    attr_accessor :watermark_bottom

    # Determines width of the watermark image. Should be specified in pixels.
    attr_accessor :watermark_width

    # Determines width of the watermark image. Should be specified in pixels.
    attr_accessor :watermark_height

    # Length of the uploaded video. Should be formatted as follows: HH:MM:SS
    attr_accessor :clip_length

    # Clip starts at a specific offset.
    attr_accessor :clip_offset

    attr_accessor :multi_chunk


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'file_size' => :'file_size',
        :'file_name' => :'file_name',
        :'extra_files' => :'extra_files',
        :'profiles' => :'profiles',
        :'path_format' => :'path_format',
        :'payload' => :'payload',
        :'extra_variables' => :'extra_variables',
        :'watermark_url' => :'watermark_url',
        :'watermark_left' => :'watermark_left',
        :'watermark_top' => :'watermark_top',
        :'watermark_right' => :'watermark_right',
        :'watermark_bottom' => :'watermark_bottom',
        :'watermark_width' => :'watermark_width',
        :'watermark_height' => :'watermark_height',
        :'clip_length' => :'clip_length',
        :'clip_offset' => :'clip_offset',
        :'multi_chunk' => :'multi_chunk'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'file_size' => :'Integer',
        :'file_name' => :'String',
        :'extra_files' => :'Array<ExtraFile>',
        :'profiles' => :'String',
        :'path_format' => :'String',
        :'payload' => :'String',
        :'extra_variables' => :'Hash<String, String>',
        :'watermark_url' => :'String',
        :'watermark_left' => :'String',
        :'watermark_top' => :'String',
        :'watermark_right' => :'String',
        :'watermark_bottom' => :'String',
        :'watermark_width' => :'String',
        :'watermark_height' => :'String',
        :'clip_length' => :'String',
        :'clip_offset' => :'String',
        :'multi_chunk' => :'BOOLEAN'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'file_size')
        self.file_size = attributes[:'file_size']
      end

      if attributes.has_key?(:'file_name')
        self.file_name = attributes[:'file_name']
      end

      if attributes.has_key?(:'extra_files')
        if (value = attributes[:'extra_files']).is_a?(Array)
          self.extra_files = value
        end
      end

      if attributes.has_key?(:'profiles')
        self.profiles = attributes[:'profiles']
      end

      if attributes.has_key?(:'path_format')
        self.path_format = attributes[:'path_format']
      end

      if attributes.has_key?(:'payload')
        self.payload = attributes[:'payload']
      end

      if attributes.has_key?(:'extra_variables')
        if (value = attributes[:'extra_variables']).is_a?(Array)
          self.extra_variables = value
        end
      end

      if attributes.has_key?(:'watermark_url')
        self.watermark_url = attributes[:'watermark_url']
      end

      if attributes.has_key?(:'watermark_left')
        self.watermark_left = attributes[:'watermark_left']
      end

      if attributes.has_key?(:'watermark_top')
        self.watermark_top = attributes[:'watermark_top']
      end

      if attributes.has_key?(:'watermark_right')
        self.watermark_right = attributes[:'watermark_right']
      end

      if attributes.has_key?(:'watermark_bottom')
        self.watermark_bottom = attributes[:'watermark_bottom']
      end

      if attributes.has_key?(:'watermark_width')
        self.watermark_width = attributes[:'watermark_width']
      end

      if attributes.has_key?(:'watermark_height')
        self.watermark_height = attributes[:'watermark_height']
      end

      if attributes.has_key?(:'clip_length')
        self.clip_length = attributes[:'clip_length']
      end

      if attributes.has_key?(:'clip_offset')
        self.clip_offset = attributes[:'clip_offset']
      end

      if attributes.has_key?(:'multi_chunk')
        self.multi_chunk = attributes[:'multi_chunk']
      else
        self.multi_chunk = true
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @file_size.nil?
        invalid_properties.push("invalid value for 'file_size', file_size cannot be nil.")
      end

      if @file_name.nil?
        invalid_properties.push("invalid value for 'file_name', file_name cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @file_size.nil?
      return false if @file_name.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          file_size == o.file_size &&
          file_name == o.file_name &&
          extra_files == o.extra_files &&
          profiles == o.profiles &&
          path_format == o.path_format &&
          payload == o.payload &&
          extra_variables == o.extra_variables &&
          watermark_url == o.watermark_url &&
          watermark_left == o.watermark_left &&
          watermark_top == o.watermark_top &&
          watermark_right == o.watermark_right &&
          watermark_bottom == o.watermark_bottom &&
          watermark_width == o.watermark_width &&
          watermark_height == o.watermark_height &&
          clip_length == o.clip_length &&
          clip_offset == o.clip_offset &&
          multi_chunk == o.multi_chunk
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [file_size, file_name, extra_files, profiles, path_format, payload, extra_variables, watermark_url, watermark_left, watermark_top, watermark_right, watermark_bottom, watermark_width, watermark_height, clip_length, clip_offset, multi_chunk].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = TelestreamCloud::Flip.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
