=begin
#Flip API

#Description

OpenAPI spec version: 3.1.0
Contact: cloudsupport@telestream.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TelestreamCloud::Flip::CloudNotificationSettingsEvents
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CloudNotificationSettingsEvents' do
  before do
    # run before each test
    @instance = TelestreamCloud::Flip::CloudNotificationSettingsEvents.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CloudNotificationSettingsEvents' do
    it 'should create an instance of CloudNotificationSettingsEvents' do
      expect(@instance).to be_instance_of(TelestreamCloud::Flip::CloudNotificationSettingsEvents)
    end
  end
  describe 'test attribute "encoding_completed"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "encoding_progress"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "video_created"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "video_encoded"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

