=begin
#Flip API

#Description

OpenAPI spec version: 3.1.0
Contact: cloudsupport@telestream.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TelestreamCloud::Flip::FactorySync
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FactorySync' do
  before do
    # run before each test
    @instance = TelestreamCloud::Flip::FactorySync.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FactorySync' do
    it 'should create an instance of FactorySync' do
      expect(@instance).to be_instance_of(TelestreamCloud::Flip::FactorySync)
    end
  end
  describe 'test attribute "syncing"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["starting", "already_started"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.syncing = value }.not_to raise_error
       #end
    end
  end

end

