=begin
#Flip API

#Description

OpenAPI spec version: 2.0.1
Contact: cloudsupport@telestream.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TelestreamCloud::Flip::FactorySyncBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FactorySyncBody' do
  before do
    # run before each test
    @instance = TelestreamCloud::Flip::FactorySyncBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FactorySyncBody' do
    it 'should create an instance of FactorySyncBody' do
      expect(@instance).to be_instance_of(TelestreamCloud::Flip::FactorySyncBody)
    end
  end
  describe 'test attribute "sync"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["true", "false"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.sync = value }.not_to raise_error
       #end
    end
  end

end

