=begin
#Flip API

#Description

OpenAPI spec version: 3.1.0
Contact: cloudsupport@telestream.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TelestreamCloud::Flip::PaginatedWorkflowsCollection
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PaginatedWorkflowsCollection' do
  before do
    # run before each test
    @instance = TelestreamCloud::Flip::PaginatedWorkflowsCollection.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaginatedWorkflowsCollection' do
    it 'should create an instance of PaginatedWorkflowsCollection' do
      expect(@instance).to be_instance_of(TelestreamCloud::Flip::PaginatedWorkflowsCollection)
    end
  end
  describe 'test attribute "workflows"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "page"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "per_page"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "total"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

