=begin
#Flip API

#Description

OpenAPI spec version: 3.1.0
Contact: cloudsupport@telestream.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TelestreamCloud::Flip::VideoMetadata
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VideoMetadata' do
  before do
    # run before each test
    @instance = TelestreamCloud::Flip::VideoMetadata.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VideoMetadata' do
    it 'should create an instance of VideoMetadata' do
      expect(@instance).to be_instance_of(TelestreamCloud::Flip::VideoMetadata)
    end
  end
end

