module TelestreamCloud
end

=begin
#Flip API

#Description

OpenAPI spec version: 3.1.0
Contact: cloudsupport@telestream.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

module TelestreamCloud::Flip
  VERSION = "1.0.0"
end
