module TelestreamCloud
end

=begin
#Flip API

#Description

OpenAPI spec version: 2.0.1
Contact: cloudsupport@telestream.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

module TelestreamCloud::Flip
  VERSION = "2.0.1"
end
