module TelestreamCloud
end

=begin
#Notifications API

#Notifications API

OpenAPI spec version: 2.0.0
Contact: cloudsupport@telestream.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

module TelestreamCloud::Notifications
  VERSION = "2.0.0"
end
