module TelestreamCloud
end

=begin
#Flip API

#Description

OpenAPI spec version: 2.0.1
Contact: cloudsupport@telestream.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'telestream_cloud_flip/api_client'
require 'telestream_cloud_flip/api_error'
require 'telestream_cloud_flip/version'
require 'telestream_cloud_flip/configuration'

# Models
require 'telestream_cloud_flip/models/canceled_response'
require 'telestream_cloud_flip/models/cloud_notification_settings'
require 'telestream_cloud_flip/models/cloud_notification_settings_events'
require 'telestream_cloud_flip/models/copy_profile_body'
require 'telestream_cloud_flip/models/count_response'
require 'telestream_cloud_flip/models/create_encoding_body'
require 'telestream_cloud_flip/models/create_video_body'
require 'telestream_cloud_flip/models/deleted_response'
require 'telestream_cloud_flip/models/encoding'
require 'telestream_cloud_flip/models/encoding_signed_url'
require 'telestream_cloud_flip/models/encoding_signed_urls'
require 'telestream_cloud_flip/models/error'
require 'telestream_cloud_flip/models/extra_file'
require 'telestream_cloud_flip/models/factory'
require 'telestream_cloud_flip/models/factory_body'
require 'telestream_cloud_flip/models/factory_body_storage_credential_attributes'
require 'telestream_cloud_flip/models/factory_sync'
require 'telestream_cloud_flip/models/factory_sync_body'
require 'telestream_cloud_flip/models/paginated_encodings_collection'
require 'telestream_cloud_flip/models/paginated_factory_collection'
require 'telestream_cloud_flip/models/paginated_profiles_collection'
require 'telestream_cloud_flip/models/paginated_video_collection'
require 'telestream_cloud_flip/models/paginated_workflows_collection'
require 'telestream_cloud_flip/models/profile'
require 'telestream_cloud_flip/models/profile_body'
require 'telestream_cloud_flip/models/resubmit_video_body'
require 'telestream_cloud_flip/models/retried_response'
require 'telestream_cloud_flip/models/signed_video_url'
require 'telestream_cloud_flip/models/update_encoding_body'
require 'telestream_cloud_flip/models/upload_session'
require 'telestream_cloud_flip/models/video'
require 'telestream_cloud_flip/models/video_metadata'
require 'telestream_cloud_flip/models/video_upload_body'

# APIs
require 'telestream_cloud_flip/api/flip_api'

# Uploader
require 'telestream_cloud_flip/uploader'

module TelestreamCloud::Flip
  class << self
    # Customize default settings for the SDK using block.
    #   TelestreamCloud::Flip.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
