module TelestreamCloud
end

=begin
#Qc API

#QC API

OpenAPI spec version: 2.0.0
Contact: cloudsupport@telestream.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

module TelestreamCloud::Qc
  VERSION = "2.0.0"
end
