module TelestreamCloud
end

=begin
#Qc API

#QC API

OpenAPI spec version: 1.0.0
Contact: cloudsupport@telestream.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

module TelestreamCloud::Qc
  VERSION = "1.0.0"
end
