=begin
#Qc API

#QC API

OpenAPI spec version: 1.0.0
Contact: cloudsupport@telestream.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TelestreamCloud::Qc::Data1
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Data1' do
  before do
    # run before each test
    @instance = TelestreamCloud::Qc::Data1.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Data1' do
    it 'should create an instance of Data1' do
      expect(@instance).to be_instance_of(TelestreamCloud::Qc::Data1)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "options"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

