=begin
#Flip API

#Description

OpenAPI spec version: 2.0.1
Contact: cloudsupport@telestream.net
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for TelestreamCloud::Flip::FlipApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FlipApi' do
  before do
    # run before each test
    @instance = TelestreamCloud::Flip::FlipApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FlipApi' do
    it 'should create an instance of FlipApi' do
      expect(@instance).to be_instance_of(TelestreamCloud::Flip::FlipApi)
    end
  end

  # unit tests for cancel_encoding
  # Cancels an Encoding.
  # 
  # @param id Id of an Encoding.
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @return [CanceledResponse]
  describe 'cancel_encoding test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for copy_profile
  # Copies a given Profile
  # 
  # @param id Id of a Profile.
  # @param factory_id Id of a Factory.
  # @param copy_profile_body 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :expand If expand option is set Profile objects will contain all command parameters, even if their value is default. By default this is not set.
  # @return [Profile]
  describe 'copy_profile test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_encoding
  # Creates an Encoding
  # 
  # @param factory_id Id of a Factory.
  # @param create_encoding_body 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :screenshots Determines whether the response will include screenshots. By default this is not set.
  # @option opts [BOOLEAN] :precise_status Determines whether the response will include a precise status. By default this is not set.
  # @return [Encoding]
  describe 'create_encoding test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_factory
  # Creates a new factory
  # 
  # @param create_factory_body 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :with_storage_provider if set to &#x60;true&#x60;, results will include a storage provider&#39;s id
  # @return [Factory]
  describe 'create_factory test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_profile
  # Creates a Profile
  # 
  # @param factory_id Id of a Factory.
  # @param create_profile_body 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :exclude_advanced_services 
  # @option opts [BOOLEAN] :expand If expand option is set Profile objects will contain all command parameters, even if their value is default. By default it is not set.
  # @return [Profile]
  describe 'create_profile test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_video
  # Creates a Video from a provided source_url.
  # 
  # @param factory_id Id of a Factory.
  # @param create_video_body 
  # @param [Hash] opts the optional parameters
  # @return [Video]
  describe 'create_video test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_workorder
  # Creates a Workorder.
  # 
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :profile_id Id of a Profile.
  # @option opts [File] :file Input file.
  # @option opts [String] :source_url URL pointing to an input file.
  # @return [nil]
  describe 'create_workorder test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_encoding
  # Deletes an Encoding from both Telestream Cloud and your storage. Returns an information whether the operation was successful.
  # 
  # @param id Id of an Encoding.
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @return [DeletedResponse]
  describe 'delete_encoding test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_profile
  # Deletes a given Profile
  # 
  # @param id Id of a Profile
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @return [DeletedResponse]
  describe 'delete_profile test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_video
  # Deletes a Video object.
  # 
  # @param id Id of a Video.
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @return [DeletedResponse]
  describe 'delete_video test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_video_source
  # Delete a video&#39;s source file.
  # 
  # @param id Id of a Video.
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @return [DeletedResponse]
  describe 'delete_video_source test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for encoding
  # Returns an Encoding object.
  # 
  # @param id Id of an Encoding.
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :screenshots Determines whether the response will include screenshots. By default this is not set.
  # @option opts [BOOLEAN] :precise_status Determines whether the response will include a precise status. By default this is not set.
  # @return [Encoding]
  describe 'encoding test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for encodings
  # Returns a list of Encoding objects
  # 
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :video_id Id of a Video. When specified, the resulting list will contain videos that belong to the Video.
  # @option opts [String] :status One of &#x60;success&#x60;, &#x60;fail&#x60;, &#x60;processing&#x60;. When specified, the resulting list will contain ecodings filtered by status.
  # @option opts [String] :profile_id Filter by profile_id.
  # @option opts [String] :profile_name Filter by profile_name.
  # @option opts [Integer] :page A page to be fetched. Default is &#x60;1&#x60;.
  # @option opts [Integer] :per_page A number of results per page. Default is &#x60;100&#x60;.
  # @option opts [BOOLEAN] :screenshots Determines whether the response will include screenshots. By default this is not set.
  # @option opts [BOOLEAN] :precise_status Determines whether the response will include a precise status. By default this is not set.
  # @return [PaginatedEncodingsCollection]
  describe 'encodings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for encodings_count
  # Returns a number of Encoding objects created using a given factory.
  # 
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @return [CountResponse]
  describe 'encodings_count test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for factories
  # Returns a collection of Factory objects.
  # Returns a collection of Factory objects.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A page to be fetched. Default is &#x60;1&#x60;.
  # @option opts [Integer] :per_page A number of results per page. Default is &#x60;100&#x60;.
  # @option opts [BOOLEAN] :with_storage_provider if set to &#x60;true&#x60;, results will include a storage provider&#39;s id
  # @return [PaginatedFactoryCollection]
  describe 'factories test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for factory
  # Returns a Factory object.
  # Returns a Factory object.
  # @param id id of a factory
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :with_storage_provider if set to &#x60;true&#x60;, results will include a storage provider&#39;s id
  # @return [Factory]
  describe 'factory test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for notifications
  # Returns a Factory&#39;s notification settings.
  # 
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @return [CloudNotificationSettings]
  describe 'notifications test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for profile
  # Returns a Profile object.
  # 
  # @param id_or_name A name or an id of a Profile.
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :expand If expand option is set Profile objects will contain all command parameters, even if their value is default. By default this is not set.
  # @return [Profile]
  describe 'profile test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for profile_encodings
  # Returns a list of Encodings that belong to a Profile.
  # 
  # @param id_or_name Id or name of a Profile.
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @return [PaginatedEncodingsCollection]
  describe 'profile_encodings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for profiles
  # Returns a collection of Profile objects.
  # 
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :exclude_advanced_services Determine whether exclude Advanced Services profiles from the results. By default this is not set.
  # @option opts [BOOLEAN] :expand If expand option is set Profile objects will contain all command parameters, even if their value is default. By default this is not set.
  # @option opts [Integer] :page A page to be fetched. Default is &#x60;1&#x60;.
  # @option opts [Integer] :per_page A number of results per page. Default is &#x60;100&#x60;.
  # @return [PaginatedProfilesCollection]
  describe 'profiles test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for queued_videos
  # Returns a collection of Video objects queued for encoding.
  # 
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A page to be fetched. Default is &#x60;1&#x60;.
  # @option opts [Integer] :per_page A number of results per page. Default is &#x60;100&#x60;.
  # @return [PaginatedVideoCollection]
  describe 'queued_videos test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for resubmit_video
  # Resubmits a video to encode.
  # Resubmits the video to encode. Please note that this option will work only for videos in &#x60;success&#x60; status.
  # @param factory_id Id of a Factory.
  # @param resubmit_video_body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'resubmit_video test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retry_encoding
  # Retries a failed encoding.
  # 
  # @param id Id of an Encoding.
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @return [RetriedResponse]
  describe 'retry_encoding test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for signed_encoding_url
  # Returns a signed url pointing to an Encoding.
  # 
  # @param id Id of an Encoding.
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @return [EncodingSignedUrl]
  describe 'signed_encoding_url test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for signed_encoding_urls
  # Returns a list of signed urls pointing to an Encoding&#39;s outputs.
  # 
  # @param id Id of an Encoding.
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @return [EncodingSignedUrls]
  describe 'signed_encoding_urls test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for signed_video_url
  # Returns a signed url pointing to a Video.
  # 
  # @param id Id of a Video.
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @return [SignedVideoUrl]
  describe 'signed_video_url test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for toggle_factory_sync
  # Toggles synchronisation settings.
  # 
  # @param id id of the factory
  # @param factory_sync_body 
  # @param [Hash] opts the optional parameters
  # @return [FactorySync]
  describe 'toggle_factory_sync test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_encoding
  # Updates an Encoding
  # 
  # @param id Id of an Encoding.
  # @param factory_id Id of a Factory.
  # @param update_encoding_body 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :screenshots Determines whether the response will include screenshots. By default this is not set.
  # @option opts [BOOLEAN] :precise_status Determines whether the response will include a precise status. By default this is not set.
  # @return [Encoding]
  describe 'update_encoding test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_factory
  # Updates a Factory&#39;s settings. Returns a Factory object.
  # 
  # @param id id of the factory
  # @param update_factory_body 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :with_storage_provider if set to &#x60;true&#x60;, results will include a storage provider&#39;s id
  # @return [Factory]
  describe 'update_factory test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_notifications
  # Updates a Factory&#39;s notification settings.
  # 
  # @param factory_id Id of a Factory.
  # @param cloud_notification_settings_body 
  # @param [Hash] opts the optional parameters
  # @return [CloudNotificationSettings]
  describe 'update_notifications test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_profile
  # Updates a given Profile
  # 
  # @param id 
  # @param factory_id Id of a Factory.
  # @param update_profile_body 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :exclude_advanced_services 
  # @option opts [BOOLEAN] :expand If expand option is set Profile objects will contain all command parameters, even if their value is default. By default this is not set.
  # @return [Profile]
  describe 'update_profile test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for upload_video
  # Creates an upload session.
  # 
  # @param factory_id Id of a Factory.
  # @param video_upload_body 
  # @param [Hash] opts the optional parameters
  # @return [UploadSession]
  describe 'upload_video test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for video
  # Returns a Video object.
  # 
  # @param id Id of a Video.
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @return [Video]
  describe 'video test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for video_encodings
  # Returns a list of Encodings that belong to a Video.
  # 
  # @param id Id of a Video.
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A page to be fetched. Default is &#x60;1&#x60;.
  # @option opts [Integer] :per_page A number of results per page. Default is &#x60;100&#x60;.
  # @option opts [BOOLEAN] :screenshots Determines whether the response will include screenshots. By default this is not set.
  # @option opts [BOOLEAN] :precise_status Determines whether the response will include a precise status. By default this is not set.
  # @return [PaginatedEncodingsCollection]
  describe 'video_encodings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for video_metadata
  # Returns a Video&#39;s metadata
  # 
  # @param id Id of a Video.
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @return [VideoMetadata]
  describe 'video_metadata test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for videos
  # Returns a collection of Video objects.
  # 
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A page to be fetched. Default is &#x60;1&#x60;.
  # @option opts [Integer] :per_page A number of results per page. Default is &#x60;100&#x60;.
  # @return [PaginatedVideoCollection]
  describe 'videos test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for workflows
  # Returns a collection of Workflows that belong to a Factory.
  # 
  # @param factory_id Id of a Factory.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A page to be fetched. Default is &#x60;1&#x60;.
  # @option opts [Integer] :per_page A number of results per page. Default is &#x60;100&#x60;.
  # @return [PaginatedWorkflowsCollection]
  describe 'workflows test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
